project_id = "kpulfxvaugjerklhqxpd"

[functions.generate-video]
verify_jwt = true

[functions.poll-video-status]
verify_jwt = false

[functions.poll-video-status.cron]
# Run every 2 minutes to check video generation status
schedule = "*/2 * * * *"

[functions.improve-prompt]
verify_jwt = false

[functions.split-prompt]
verify_jwt = false

[functions.categorize-prompt]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
